import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-6`}>
        <nav>
          <ul className="flex gap-6 mb-6">
            <li>
              {" "}
              <Link href="/"> Home | </Link>
            </li>
            <li>
              {" "}
              <Link href="/about">About | </Link>
            </li>
            <li>
              {" "}
              <Link href="/blogs">Blogs | </Link>
            </li>
            <li>
              {" "}
              <Link href="/posts">Posts | </Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
