import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";

const geistSans = Mulish({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Framer Motion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased`}>{children}</body>
    </html>
  );
}
