import { Inter } from "next/font/google";
import "./globals.css";
import StoreContextMain from "./context/StoreContextMain";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MoveSeeks Flights",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreContextMain> {children}</StoreContextMain>
      </body>
    </html>
  );
}
