import { Inter } from "next/font/google";
import "./globals.css";

import { Auth0Provider } from "@auth0/auth0-react";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {" "}
        <Auth0Provider
          domain="dev-tanvir.us.auth0.com"
          clientId="FfdzXl9s30k3IhqPwNlwke93nVj7TyZw"
          authorizationParams={{
            redirect_uri: window.location.origin,
          }}
        >
          {children}{" "}
        </Auth0Provider>
      </body>
    </html>
  );
}
