import type { Metadata } from "next";
import { Geist, Geist_Mono, Doto, Rochester } from "next/font/google";
import "./globals.css";

const geistSans = Doto({ subsets: ["latin"], weight: "400" });
// console.log(geistSans);

export const metadata: Metadata = {
  title: "Framer Motion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className}   antialiased`}>{children}</body>
    </html>
  );
}
